# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i electron-builder -g
    - run: npm install
    - run: npm run build-win64
    - run: npm run build-win
    - name: Release build
  # You may pin to the exact commit or the version.
  # uses: HEPTAhu/upload_github_release_assets_action@93feb159382a1b8a44c93b5afc48f046effd3960
      uses: HEPTAhu/upload_github_release_assets_action@v0.0.5
      with:
    # Note-worthy description of changes in release
        body: Test!
    # Gives the release a custom name. Defaults to tag name
        name: test-release
    # Gives a tag name. Defaults to github.GITHUB_REF
        tag_name: v1.0.0
    # A file, directory or wildcard pattern that describes what to upload
        path: ./dist/*.exe
    # Authorized secret GitHub Personal Access Token. Defaults to github.token
        token: ${{ secrets.token }}
        append_body: true
          
          
    
