# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build for Linux

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

env:
  GH_TOKEN:
    ${{ secrets.token }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo npm i electron-builder -g
    - run: npm install
    - run: sudo npm run build-linux
    - name: Release build
      uses: HEPTAhu/upload_github_release_assets_action@v0.0.5
      with:
        body: "Full changelog: <https://github.com/User782Tec/Desktop-icon-tools/commits/${{ github.ref_name }}>"
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        path: ./dist/*.AppImage
        token: ${{ secrets.token }}
    - run: sudo npm run build-linux-deb
    - name: Release build
      uses: HEPTAhu/upload_github_release_assets_action@v0.0.5
      with:
        body: "Full changelog: <https://github.com/User782Tec/Desktop-icon-tools/commits/${{ github.ref_name }}>"
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        path: ./dist/*.deb
        token: ${{ secrets.token }}
    - run: sudo npm run build-linux-rpm
    - name: Release build
      uses: HEPTAhu/upload_github_release_assets_action@v0.0.5
      with:
        body: "Full changelog: <https://github.com/User782Tec/Desktop-icon-tools/commits/${{ github.ref_name }}>"
        name: ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        path: ./dist/*.rpm
        token: ${{ secrets.token }}
