# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env: 
  GH_TOKEN: ${{ secrets.token }}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: sudo npm i electron-builder -g
    - run: npm install
    - run: sudo npm run build-linux
    - name: GitHub Releases
  # You may pin to the exact commit or the version.
  # uses: fnkr/github-action-ghr@96b1448dc6162f370067e1de51e856e733a76b4f
      uses: fnkr/github-action-ghr@v1.3
      env:
        GHR_PATH: dist/desktop-icon-tools-1.0.0.AppImage
        GITHUB_TOKEN: ${{ secrets.token }}
          
    
